name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Test
    if: "${{ !endsWith(github.actor, '[bot]') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - name: Run golangci-lint
        uses: projectdiscovery/actions/golangci-lint/v2@v1
        with:
          version: latest
          args: --timeout 5m
          working-directory: .

  build:
    name: Test Builds
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build .
        working-directory: cmd/pdtm/

      - name: Test
        run: go test ./...
        working-directory: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Race Condition Tests
        run: go run -race .
        working-directory: cmd/pdtm/
      
      - name: Test Example Code
        run: go run .
        working-directory: examples/
